name: lashaundale.com
favicon: null
layout_spectrum: 0.75109
typography_spectrum: 0.18755
title: lashaundale.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#5eb1e3'
    - '#fdc346'
    - '#b8d7f1'
    - '#ff7f00'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
