name: lashaundale.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18755
title: lashaundale.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#74c7e5'
    - '#fdc71d'
    - '#a5a28d'
    - '#1a1c1a'
    - '#517e8d'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
