name: lashaundale.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74383
title: lashaundale.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#60c2a9'
    - '#fbfbfb'
    - '#e4001c'
    - '#1b1482'
    - '#ca6075'
  brandStrength: 0.8751736648846418
  lightness: 0.11654517357237637
  saturation: 0.6217880186159164
  rhythmicContrast: 0.8256649698596448
purpose: []
