name: lashaundale.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18755
title: lashaundale.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010504'
    - '#007775'
    - '#4bb9a1'
    - '#e6fed4'
    - '#849670'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
