name: lashaundale.com
favicon: null
layout_spectrum: 0.2373
typography_spectrum: 0.546595
title: fullyinspired
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#47c0e7'
    - '#f8dd34'
    - '#dfe2cd'
    - '#68c2ea'
    - '#193c48'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
