name: lashaundale.com
favicon: null
layout_spectrum: 0.75109
typography_spectrum: 0.18755
title: lashaundale.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c4c4c2'
    - '#00b4c5'
    - '#847d73'
    - '#2a303d'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
