name: lashaundale.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59697
title: lashaundale.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#375456'
    - '#1d2c2c'
    - '#9bccd9'
    - '#030404'
    - '#848782'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0
  rhythmicContrast: 1
purpose: []
