name: lashaundale.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.546595
title: lashaundale.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#18593c'
    - '#aa9794'
    - '#8ab223'
    - '#dbd1ce'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
