name: lashaundale.com
favicon: null
layout_spectrum: 0.4971
typography_spectrum: 0.18755
title: lashaundale.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1f4e75'
    - '#99fdf9'
    - '#47c183'
    - '#738417'
  brandStrength: 0.875
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
